// DraftKings MLB Classic configuration
export const DK_CONFIG = {
  name: 'DraftKings',
  shortName: 'DK',
  salaryCap: 50000,
  rosterSize: 10,
  positions: ['P', 'P', 'C', '1B', '2B', '3B', 'SS', 'OF', 'OF', 'OF'],
  positionLabels: {
    P: 'Pitcher',
    C: 'Catcher',
    '1B': 'First Base',
    '2B': 'Second Base',
    '3B': 'Third Base',
    SS: 'Shortstop',
    OF: 'Outfield',
  },
  scoring: {
    single: 3,
    double: 5,
    triple: 8,
    homeRun: 10,
    rbi: 2,
    run: 2,
    walk: 2,
    hbp: 2,
    stolenBase: 5,
    caughtStealing: -2,
    // Pitching
    inningPitched: 2.25,
    strikeout: 2,
    earnedRun: -2,
    hit: -0.6,
    walkPitching: -0.6,
    hbpPitching: -0.6,
    win: 4,
    completeGameBonus: 2.5,
    cgShutoutBonus: 2.5,
    noHitterBonus: 5,
  },
};

// FanDuel MLB configuration
export const FD_CONFIG = {
  name: 'FanDuel',
  shortName: 'FD',
  salaryCap: 35000,
  rosterSize: 9,
  positions: ['P', 'C/1B', '2B', '3B', 'SS', 'OF', 'OF', 'OF', 'UTIL'],
  positionLabels: {
    P: 'Pitcher',
    'C/1B': 'Catcher/First Base',
    '2B': 'Second Base',
    '3B': 'Third Base',
    SS: 'Shortstop',
    OF: 'Outfield',
    UTIL: 'Utility',
  },
  scoring: {
    single: 3,
    double: 6,
    triple: 9,
    homeRun: 12,
    rbi: 3.5,
    run: 3.2,
    walk: 3,
    hbp: 3,
    stolenBase: 6,
    caughtStealing: -3,
    // Pitching
    win: 6,
    earnedRun: -3,
    strikeout: 3,
    inningPitched: 3,
    qualityStart: 4,
  },
};

// All MLB teams
export const MLB_TEAMS = [
  { abbr: 'ARI', name: 'Arizona Diamondbacks', short: 'Diamondbacks' },
  { abbr: 'ATL', name: 'Atlanta Braves', short: 'Braves' },
  { abbr: 'BAL', name: 'Baltimore Orioles', short: 'Orioles' },
  { abbr: 'BOS', name: 'Boston Red Sox', short: 'Red Sox' },
  { abbr: 'CHC', name: 'Chicago Cubs', short: 'Cubs' },
  { abbr: 'CHW', name: 'Chicago White Sox', short: 'White Sox' },
  { abbr: 'CIN', name: 'Cincinnati Reds', short: 'Reds' },
  { abbr: 'CLE', name: 'Cleveland Guardians', short: 'Guardians' },
  { abbr: 'COL', name: 'Colorado Rockies', short: 'Rockies' },
  { abbr: 'DET', name: 'Detroit Tigers', short: 'Tigers' },
  { abbr: 'HOU', name: 'Houston Astros', short: 'Astros' },
  { abbr: 'KC', name: 'Kansas City Royals', short: 'Royals' },
  { abbr: 'LAA', name: 'Los Angeles Angels', short: 'Angels' },
  { abbr: 'LAD', name: 'Los Angeles Dodgers', short: 'Dodgers' },
  { abbr: 'MIA', name: 'Miami Marlins', short: 'Marlins' },
  { abbr: 'MIL', name: 'Milwaukee Brewers', short: 'Brewers' },
  { abbr: 'MIN', name: 'Minnesota Twins', short: 'Twins' },
  { abbr: 'NYM', name: 'New York Mets', short: 'Mets' },
  { abbr: 'NYY', name: 'New York Yankees', short: 'Yankees' },
  { abbr: 'OAK', name: 'Oakland Athletics', short: 'Athletics' },
  { abbr: 'PHI', name: 'Philadelphia Phillies', short: 'Phillies' },
  { abbr: 'PIT', name: 'Pittsburgh Pirates', short: 'Pirates' },
  { abbr: 'SD', name: 'San Diego Padres', short: 'Padres' },
  { abbr: 'SF', name: 'San Francisco Giants', short: 'Giants' },
  { abbr: 'SEA', name: 'Seattle Mariners', short: 'Mariners' },
  { abbr: 'STL', name: 'St. Louis Cardinals', short: 'Cardinals' },
  { abbr: 'TB', name: 'Tampa Bay Rays', short: 'Rays' },
  { abbr: 'TEX', name: 'Texas Rangers', short: 'Rangers' },
  { abbr: 'TOR', name: 'Toronto Blue Jays', short: 'Blue Jays' },
  { abbr: 'WSH', name: 'Washington Nationals', short: 'Nationals' },
];

export const POSITIONS = ['P', 'C', '1B', '2B', '3B', 'SS', 'OF'];

export const POSITION_COLORS = {
  P: '#ef4444',
  C: '#f59e0b',
  '1B': '#10b981',
  '2B': '#3b82f6',
  '3B': '#8b5cf6',
  SS: '#ec4899',
  OF: '#06b6d4',
  UTIL: '#6b7280',
  'C/1B': '#f59e0b',
};
